services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    hostname: rmq
    ports:
      - "15672:15672" # RabbitMQ management web UI
      - "5672:5672"    # RabbitMQ AMQP protocol
    restart: unless-stopped
    # wait for RabbitMQ to be fully initialized before other services (like Uvicorn) proceed
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
  
  mongoose:
    image: mongo:latest
    container_name: mongoose
    ports:
      - "27017:27017" # MongoDB default port
    restart: unless-stopped
