[project]
authors = ["octocroc <crctpus@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "bkpmgt"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
strawberry-graphql = ">=0.253.0,<0.254"
motor = ">=3.6.0,<4"
fastapi = ">=0.115.5,<0.116"
uvicorn = ">=0.32.1,<0.33"
websockets = ">=14.1,<15"
aio-pika = ">=9.4.3,<10"
pyjwt = ">=2.10.0,<3"
requests = ">=2.32.3,<3"
boto3 = ">=1.35.68,<2"
cryptography = ">=43.0.3,<44"
aiosqlite = ">=0.20.0,<0.21"
commentjson = ">=0.9.0,<0.10"
apscheduler = ">=3.10.4,<4"
sqlalchemy = ">=2.0.36,<3"
pyinstaller = ">=6.11.1,<7"
